arm

diff --git a/.github/workflows/all.yaml b/.github/workflows/all.yaml
--- a/.github/workflows/all.yaml
+++ b/.github/workflows/all.yaml
@@ -14,126 +14,126 @@ env:
    PERL_CARTON_PATH: $GITHUB_WORKSPACE/local
 
 jobs:
-  linux:
-    runs-on: ubuntu-latest
-
-    strategy:
-      fail-fast: false
-      matrix:
-        perl-version:
-          - '5.34'
-          - '5.32'
-          - '5.30'
-          - '5.28'
-          - '5.26'
-          - '5.24'
-          - '5.22'
-          - '5.20'
-          - '5.18'
-          - '5.16'
-          - '5.14'
-          - '5.12'
-          - '5.10'
-
-    container:
-      image: perldocker/perl-tester:${{ matrix.perl-version }}
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: perl -V
-        run: perl -V
-      - name: Install ICU
-        run: apt install -y libicu-dev
-      - name: Install Dependencies
-        run: cpanm --notest --installdeps --with-configure --with-develop .
-      - name: perl Makefile.PL
-        run: perl Makefile.PL
-      - name: make
-        run: make
-      - name: Run Tests
-        run: prove -wlvmb t
-
-  linux-specialperls:
-    runs-on: ubuntu-latest
-
-    strategy:
-      fail-fast: false
-      matrix:
-        perl-version:
-          - '5.020.003'
-          #- '5.022.004'    # no quadmath
-          - '5.024.004'
-          - '5.026.003'
-          - '5.028.003'
-          - '5.030.003'
-          - '5.032.001'
-        perl-type:
-          - 'main-longdouble-buster'
-          - 'main-quadmath-buster'
-
-    container:
-      image: simcop2387/perl-tester:${{ matrix.perl-version }}-${{ matrix.perl-type }}
-
-    steps:
-      - uses: actions/checkout@v3
-      - run: perl -V
-      - run: apt update
-      - run: apt install -y curl libicu-dev pkg-config
-      - name: Install Dependencies
-        run: curl -L https://cpanmin.us | perl - --notest --installdeps --with-configure --with-develop .
-      - name: perl Makefile.PL
-        run: perl Makefile.PL
-      - name: make
-        run: make
-      - name: Run Tests
-        run: prove -wlvmb t
-
-  # CloudLinux 6
-  linux-icu-4-2-1:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://sourceforge.net/projects/icu/files/ICU4C/4.2.1/icu4c-4_2_1-src.tgz/download
-      create_pkg_config_version: 4.2.1
-
-  linux-icu-4-4-2:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://sourceforge.net/projects/icu/files/ICU4C/4.4.2/icu4c-4_4_2-src.tgz/download
-      create_pkg_config_version: 4.4.2
-
-  linux-icu-4-6-1:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://sourceforge.net/projects/icu/files/ICU4C/4.6.1/icu4c-4_6_1-src.tgz/download
-      #create_pkg_config_version: 4.6.1
-
-  linux-icu-4-8:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://sourceforge.net/projects/icu/files/ICU4C/4.8/icu4c-4_8-src.tgz/download
-      #create_pkg_config_version: 4.8
-
-  linux-icu-49-1-2:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://sourceforge.net/projects/icu/files/ICU4C/49.1/icu4c-49_1-src.tgz/download
-
-  # CentOS/RHEL 7
-  linux-icu-50-2:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://github.com/unicode-org/icu/releases/download/release-50-2/icu4c-50_2-src.tgz
-
-  # CentOS/RHEL 8
-  linux-icu-60-3:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://github.com/unicode-org/icu/releases/download/release-60-3/icu4c-60_3-src.tgz
-
-  linux-icu-70-1:
-    uses: ./.github/workflows/reusable_defined_icu.yaml
-    with:
-      url: https://github.com/unicode-org/icu/releases/download/release-70-1/icu4c-70_1-src.tgz
+#  linux:
+#    runs-on: ubuntu-latest
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        perl-version:
+#          - '5.34'
+#          - '5.32'
+#          - '5.30'
+#          - '5.28'
+#          - '5.26'
+#          - '5.24'
+#          - '5.22'
+#          - '5.20'
+#          - '5.18'
+#          - '5.16'
+#          - '5.14'
+#          - '5.12'
+#          - '5.10'
+#
+#    container:
+#      image: perldocker/perl-tester:${{ matrix.perl-version }}
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: perl -V
+#        run: perl -V
+#      - name: Install ICU
+#        run: apt install -y libicu-dev
+#      - name: Install Dependencies
+#        run: cpanm --notest --installdeps --with-configure --with-develop .
+#      - name: perl Makefile.PL
+#        run: perl Makefile.PL
+#      - name: make
+#        run: make
+#      - name: Run Tests
+#        run: prove -wlvmb t
+#
+#  linux-specialperls:
+#    runs-on: ubuntu-latest
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        perl-version:
+#          - '5.020.003'
+#          #- '5.022.004'    # no quadmath
+#          - '5.024.004'
+#          - '5.026.003'
+#          - '5.028.003'
+#          - '5.030.003'
+#          - '5.032.001'
+#        perl-type:
+#          - 'main-longdouble-buster'
+#          - 'main-quadmath-buster'
+#
+#    container:
+#      image: simcop2387/perl-tester:${{ matrix.perl-version }}-${{ matrix.perl-type }}
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - run: perl -V
+#      - run: apt update
+#      - run: apt install -y curl libicu-dev pkg-config
+#      - name: Install Dependencies
+#        run: curl -L https://cpanmin.us | perl - --notest --installdeps --with-configure --with-develop .
+#      - name: perl Makefile.PL
+#        run: perl Makefile.PL
+#      - name: make
+#        run: make
+#      - name: Run Tests
+#        run: prove -wlvmb t
+#
+#  # CloudLinux 6
+#  linux-icu-4-2-1:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://sourceforge.net/projects/icu/files/ICU4C/4.2.1/icu4c-4_2_1-src.tgz/download
+#      create_pkg_config_version: 4.2.1
+#
+#  linux-icu-4-4-2:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://sourceforge.net/projects/icu/files/ICU4C/4.4.2/icu4c-4_4_2-src.tgz/download
+#      create_pkg_config_version: 4.4.2
+#
+#  linux-icu-4-6-1:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://sourceforge.net/projects/icu/files/ICU4C/4.6.1/icu4c-4_6_1-src.tgz/download
+#      #create_pkg_config_version: 4.6.1
+#
+#  linux-icu-4-8:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://sourceforge.net/projects/icu/files/ICU4C/4.8/icu4c-4_8-src.tgz/download
+#      #create_pkg_config_version: 4.8
+#
+#  linux-icu-49-1-2:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://sourceforge.net/projects/icu/files/ICU4C/49.1/icu4c-49_1-src.tgz/download
+#
+#  # CentOS/RHEL 7
+#  linux-icu-50-2:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://github.com/unicode-org/icu/releases/download/release-50-2/icu4c-50_2-src.tgz
+#
+#  # CentOS/RHEL 8
+#  linux-icu-60-3:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://github.com/unicode-org/icu/releases/download/release-60-3/icu4c-60_3-src.tgz
+#
+#  linux-icu-70-1:
+#    uses: ./.github/workflows/reusable_defined_icu.yaml
+#    with:
+#      url: https://github.com/unicode-org/icu/releases/download/release-70-1/icu4c-70_1-src.tgz
 
   qemu:
     runs-on: ubuntu-latest
@@ -142,77 +142,77 @@ jobs:
       fail-fast: false
       matrix:
         platform:
-          - s390x
+#          - s390x
           - arm32v7
 
     steps:
       - name: Get the qemu container
         run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
       - name: Run tests on ${{ matrix.platform }}
-        run: docker run --rm --interactive ${{ matrix.platform }}/ubuntu bash -c "export DEBIAN_FRONTEND=noninteractive; apt update; apt install -y curl perl make git gcc libicu-dev pkg-config 'g++'; git clone --recurse-submodules $GITHUB_SERVER_URL/$GITHUB_REPOSITORY; cd $( echo $GITHUB_REPOSITORY | cut -d/ -f2 ); git checkout $GITHUB_HEAD_REF; curl -L https://cpanmin.us | perl - --notest --installdeps --with-configure .; perl Makefile.PL; make; prove -wlvmb t"
+        run: docker run --rm --interactive ${{ matrix.platform }}/ubuntu bash -c "export DEBIAN_FRONTEND=noninteractive; apt update && apt install -y curl perl make git gcc libicu-dev pkg-config 'g++' && git clone --recurse-submodules $GITHUB_SERVER_URL/$GITHUB_REPOSITORY && cd $( echo $GITHUB_REPOSITORY | cut -d/ -f2 ) && echo 'Checking out' $GITHUB_HEAD_REF && git checkout $GITHUB_HEAD_REF && curl -L https://cpanmin.us | perl - --notest --installdeps --with-configure . && perl Makefile.PL && make && prove -wlvmb t"
 
-  freebsd:
-    runs-on: macos-10.15
-    steps:
-    - uses: actions/checkout@v3
-    - uses: vmactions/freebsd-vm@v0.1.6
-      with:
-        prepare: pkg install -y p5-ExtUtils-PkgConfig curl icu
-        run: |
-            perl -V
-            curl -L https://cpanmin.us | perl - --notest --installdeps --with-develop --with-configure .
-            perl Makefile.PL
-            make
-            prove -wlvmb t
-
-  mac:
-    runs-on: macOS-latest
-
-    steps:
-      - uses: actions/checkout@v3
-      - name: Set up Perl
-        run: brew install perl
-      - name: perl -V
-        run: perl -V
-      - name: Install Dependencies
-        run: curl -L https://cpanmin.us | perl - --notest --installdeps --with-develop --with-configure .
-      - name: perl Makefile.PL
-        run: perl Makefile.PL
-        env:
-          PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
-      - name: make
-        run: make
-      - name: Run tests (with coverage)
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          curl -L https://cpanmin.us | perl - --notest Devel::Cover::Report::Coveralls
-          `perl -MConfig -E'print $Config::Config{"sitebin"}'`/cover -test -report Coveralls
-
-  cygwin:
-    runs-on: windows-latest
-
-    steps:
-      - name: Set up Cygwin
-        uses: egor-tensin/setup-cygwin@v3
-        with:
-            platform: x64
-            packages: perl_base perl-ExtUtils-MakeMaker make gcc-g++ libcrypt-devel libnsl-devel bash libicu-devel
-      - uses: actions/checkout@v3
-      - run: perl -V
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-      - run: cpan App::cpanminus
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-      - name: Install Dependencies
-        run: cd $GITHUB_WORKSPACE; cpanm --verbose --notest --installdeps --with-configure --with-develop .
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-      - name: perl Makefile.PL
-        run: cd $GITHUB_WORKSPACE; perl Makefile.PL
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-      - name: make
-        run: cd $GITHUB_WORKSPACE; make
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-      - name: prove -wlvmb t
-        run: cd $GITHUB_WORKSPACE; make test
-        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
-
+#  freebsd:
+#    runs-on: macos-10.15
+#    steps:
+#    - uses: actions/checkout@v3
+#    - uses: vmactions/freebsd-vm@v0.1.6
+#      with:
+#        prepare: pkg install -y p5-ExtUtils-PkgConfig curl icu
+#        run: |
+#            perl -V
+#            curl -L https://cpanmin.us | perl - --notest --installdeps --with-develop --with-configure .
+#            perl Makefile.PL
+#            make
+#            prove -wlvmb t
+#
+#  mac:
+#    runs-on: macOS-latest
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: Set up Perl
+#        run: brew install perl
+#      - name: perl -V
+#        run: perl -V
+#      - name: Install Dependencies
+#        run: curl -L https://cpanmin.us | perl - --notest --installdeps --with-develop --with-configure .
+#      - name: perl Makefile.PL
+#        run: perl Makefile.PL
+#        env:
+#          PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
+#      - name: make
+#        run: make
+#      - name: Run tests (with coverage)
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          curl -L https://cpanmin.us | perl - --notest Devel::Cover::Report::Coveralls
+#          `perl -MConfig -E'print $Config::Config{"sitebin"}'`/cover -test -report Coveralls
+#
+#  cygwin:
+#    runs-on: windows-latest
+#
+#    steps:
+#      - name: Set up Cygwin
+#        uses: egor-tensin/setup-cygwin@v3
+#        with:
+#            platform: x64
+#            packages: perl_base perl-ExtUtils-MakeMaker make gcc-g++ libcrypt-devel libnsl-devel bash libicu-devel
+#      - uses: actions/checkout@v3
+#      - run: perl -V
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#      - run: cpan App::cpanminus
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#      - name: Install Dependencies
+#        run: cd $GITHUB_WORKSPACE; cpanm --verbose --notest --installdeps --with-configure --with-develop .
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#      - name: perl Makefile.PL
+#        run: cd $GITHUB_WORKSPACE; perl Makefile.PL
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#      - name: make
+#        run: cd $GITHUB_WORKSPACE; make
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#      - name: prove -wlvmb t
+#        run: cd $GITHUB_WORKSPACE; make test
+#        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+#
